# Generated by Django 4.2.2 on 2024-03-07 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.ImageField(upload_to='images')),
                ('image_date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
